### PR TITLE
Update DB Class to Prevent Collisions

### PR DESCRIPTION
**Pull request by thezenmonkey**
The Database class should be updated to SS_Color. Color by itself is too generic and caused collisions with other modules (yes, they should rename their classes as well)

### CODE REVIEW

**Comment by colymba** [comment]
Sounds like a great idea! Just wondering if "SS" is the right prefix? I would imagine SilverStripe themselves would like to reserve this? Maybe something related to the module name would be better?

Or was the collision with non SS related classes?

**Comment by thezenmonkey** [comment]
I was using [titledk/silverstripe-calendar](https://github.com/titledk/silverstripe-calendar) which uses a Color class to define item coloring. I figured SS may work since SilverStripe uses it for the Date field to prevent it from conflicting with the PHP function. I'm not sure if they're reserving the SS convention for framework only. I'll post it to the google group.

**Comment by colymba** [comment]
I'll merge this anyway. We can change the SS_ prefix later if needed....

**Comment by thezenmonkey** [comment]
Looks like moving forward they'll be using namespacing and prefixing with DB, so DBColor. Namespaing causes issues with SSViewer now so that will be a little way off. https://github.com/silverstripe/silverstripe-framework/pull/4551

I'll ammend the PR

**Pull request merged**
